export { default as SecondSection } from './SecondSection'
export { default as ThirdSection } from './ThirdSection'
export { default as FourthSection } from './FourthSection'
export { default as FifthSection } from './FifthSection'
export { default as Header } from './Header'
export { default as CargoVideoSection } from './VideoSection'