export { default as TextMoad } from './TextMoad'
export { default as TextCargo } from './TextCargo'
export { default as SecondMobileSvg } from './SecondMobileSvg'
export { default as DownArrow } from './DownArrow'
export { default as MobileOne } from './MobileOne'
export { default as MobileTwo } from './MobileTwo'
export { default as MobileThree } from './MobileThree'
export { default as Logo} from './Logo'
export {default as TextAdvertisement} from './TextAdvertisement'
export {default as WhiteDot} from './WhiteDot'
export {default as ActiveDot} from './ActiveDot'
export {default as RightArrow} from './RightArrow'
export {default as SubmitIcon} from './SubmitIcon'